---
- name: Create exporter system user.
  ansible.builtin.user:
    name: "{{ prometheus_postgres_system_user }}"
    comment: "Prometheus postgres exporter"
    system: true
    shell: /bin/false
    create_home: false
  when: prometheus_postgres_system_user != 'postgres'

- name: Create postgres exporter directories.
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /opt/prometheus/postgres
    - /etc/prometheus

- name: Check current postgres_exporter version.
  ansible.builtin.command:
    cmd: /opt/prometheus/postgres_exporter/postgres_exporter --version
  register: _exporter_version_check
  changed_when: false
  failed_when: false

- name: Download and install postgres_exporter.
  when: >-
    _exporter_version_check.rc != 0 or
    prometheus_postgres_version not in (_exporter_version_check.stderr | default(''))
  block:
    - name: Get checksums from GitHub.
      ansible.builtin.set_fact:
        _checksum_list: >-
          {{ lookup('url',
            'https://github.com/prometheus-community/postgres_exporter/releases/download/v'
            + prometheus_postgres_version + '/sha256sums.txt',
            wantlist=True) | list }}
      delegate_to: localhost
      run_once: true

    - name: Extract checksum for {{ go_arch }}.
      ansible.builtin.set_fact:
        _exporter_checksum: "{{ item.split(' ')[0] }}"
      loop: "{{ _checksum_list }}"
      when: "('linux-' + go_arch + '.tar.gz') in item"
      delegate_to: localhost

    - name: Download postgres_exporter binary.
      become: true
      ansible.builtin.get_url:
        url: >-
          https://github.com/prometheus-community/postgres_exporter/releases/download/v{{
            prometheus_postgres_version }}/postgres_exporter-{{
            prometheus_postgres_version }}.linux-{{ go_arch }}.tar.gz
        checksum: "sha256:{{ _exporter_checksum }}"
        dest: >-
          /opt/prometheus/postgres_exporter-{{
            prometheus_postgres_version }}.linux-{{ go_arch }}.tar.gz
        mode: "0644"

    - name: Extract postgres_exporter archive.
      become: true
      ansible.builtin.unarchive:
        src: >-
          /opt/prometheus/postgres_exporter-{{
            prometheus_postgres_version }}.linux-{{ go_arch }}.tar.gz
        dest: /opt/prometheus
        owner: root
        group: root
        remote_src: true

- name: Symlink postgres_exporter to current version.
  become: true
  ansible.builtin.file:
    src: >-
      /opt/prometheus/postgres_exporter-{{
        prometheus_postgres_version }}.linux-{{ go_arch }}
    path: /opt/prometheus/postgres_exporter
    force: true
    state: link
  notify: Restart prometheus-postgres-exporter.

- name: Assemble legacy query configuration file.
  become: true
  ansible.builtin.assemble:
    dest: "{{ prometheus_postgres_extend_query_path }}"
    regexp: "^{{ prometheus_postgres_query_filenames | join('|') }}$"
    remote_src: false
    src: "{{ prometheus_postgres_query_directory }}"
    mode: "0644"
  when:
    - prometheus_postgres_extend_query_path | length > 0
    - prometheus_postgres_query_filenames | length > 0
  notify: Restart prometheus-postgres-exporter.

- name: Deploy systemd service unit.
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system/prometheus-postgres-exporter.service
    src: systemd-system-prometheus-postgres-exporter-service.j2
    mode: "0644"
  notify: Restart prometheus-postgres-exporter.

- name: Ensure prometheus-postgres-exporter is started and enabled.
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: "{{ prometheus_postgres_enabled }}"
    name: prometheus-postgres-exporter.service
    state: "{{ prometheus_postgres_state }}"
