---
- name: Restart prometheus-postgres-exporter.
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus-postgres-exporter.service
    state: "{{ prometheus_postgres_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
