---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: prometheus-postgres
    image: eniocarboni/docker-rockylinux-systemd:9
    image_version: latest
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: testinfra
